### PR TITLE
write-docs

### PR DESCRIPTION
**Pull request by ydidwania**

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
perfect :)

**Comment by djmitche** [comment]
Hm,
```

Aug 27 16:34:28 taskcluster-events app/web.1: TypeError: builder.reference is not a function 
Aug 27 16:34:28 taskcluster-events app/web.1:     at setup (/app/src/main.js:39:30) 
Aug 27 16:34:28 taskcluster-events app/web.1:     at /app/node_modules/taskcluster-lib-loader/lib/loader.js:337:28 
Aug 27 16:34:28 taskcluster-events app/web.1:     at tryCallOne (/app/node_modules/promise/lib/core.js:37:12) 
Aug 27 16:34:28 taskcluster-events app/web.1:     at /app/node_modules/promise/lib/core.js:123:15 
Aug 27 16:34:28 taskcluster-events app/web.1:     at flush (/app/node_modules/asap/raw.js:50:29) 
Aug 27 16:34:28 taskcluster-events app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:131:7) 
Aug 27 16:34:28 taskcluster-events app/web.1:     at process._tickDomainCallback (internal/process/next_tick.js:218:9) 
Aug 27 16:34:28 taskcluster-events app/web.1:     at Function.Module.runMain (module.js:695:11) 
Aug 27 16:34:28 taskcluster-events app/web.1:     at startup (bootstrap_node.js:191:16) 
Aug 27 16:34:28 taskcluster-events app/web.1:     at bootstrap_node.js:612:3 
```

**Comment by djmitche** [comment]
Ah, I see, it's because it's using an older version of tc-lib-api (11.x, so missing [this](https://github.com/taskcluster/taskcluster-lib-api/commit/c61d80522f0de6636929335706cd8aa746d0b678))

**Comment by djmitche** [comment]
I reverted this merge.  There are other changes necessary to upgrade to the latest tc-lib-api, along with some testing.  Once that's done, this patch will probably apply without any conflicts!

**Comment by ydidwania** [comment]
is tc-lib-api v12.3.2 a stable release ?
And do we need `references` here, considering this is not a conventional API?

**Comment by djmitche** [comment]
Yes, and yes :)

11.x was also stable -- it just didn't support `builder.references()` :)

**Pull request merged**
